sudo: required
services:
    - docker

before_install:
    - docker build -t babillie/multi-docker-test/ -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true babillie/multi-docker-test npm run test

 after_success:
    - docker build -t babillie/multi-client ./client
    - docker build -t babillie/multi-nginx ./nginx
    - docker build -t babillie/multi-server ./server
    - docker build -t babillie/multi-worker ./worker

# login to the docker cli
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to docker hub
- docker push babillie/multi-client
- docker push babillie/multi-nginx
- docker push babillie/multi-server
- docker push babillie/multi-worker